var ide = 0;
global.mayel[ide,0] = "Normal"; //Nombre
global.mayel[ide,1] = ""; //Descripcion
global.mayel[ide,2] = 0; //Coste
global.mayel[ide,3] = spr_mayel_parado; //Sprite parado
global.mayel[ide,4] = spr_mayel_caminando; //Sprite caminando
global.mayel[ide,5] = spr_mayel_saltando_inicio; //Sprite inicio
global.mayel[ide,6] = spr_mayel_saltando_caida; //Sprite caida
global.mayel[ide,7] = spr_mayel_saltando_aterrizar; //Sprite aterrizar
global.mayel[ide,8] = 0; //Bloqueada

var ide = 1;
global.mayel[ide,0] = "Casco"; //Nombre
global.mayel[ide,1] = ""; //Descripcion
global.mayel[ide,2] = 0; //Coste
global.mayel[ide,3] = spr_mayelcasco_parado; //Sprite parado
global.mayel[ide,4] = spr_mayelcasco_caminando; //Sprite caminando
global.mayel[ide,5] = spr_mayelcasco_saltando_inicio; //Sprite inicio
global.mayel[ide,6] = spr_mayelcasco_saltando_caida; //Sprite caida
global.mayel[ide,7] = spr_mayelcasco_saltando_aterrizar; //Sprite aterrizar
global.mayel[ide,8] = 0; //Bloqueada

var ide = 2;
global.mayel[ide,0] = "Tuffie"; //Nombre
global.mayel[ide,1] = ""; //Descripcion
global.mayel[ide,2] = 0; //Coste
global.mayel[ide,3] = spr_mayeltuffie_parado; //Sprite parado
global.mayel[ide,4] = spr_mayeltuffie_caminando; //Sprite caminando
global.mayel[ide,5] = spr_mayeltuffie_saltando_inicio; //Sprite inicio
global.mayel[ide,6] = spr_mayeltuffie_saltando_caida; //Sprite caida
global.mayel[ide,7] = spr_mayeltuffie_saltando_aterrizar; //Sprite aterrizar
global.mayel[ide,8] = 0; //Bloqueada